### ISSUE TITLE
Im not able to see stats of myself or group members

### ISSUE THREAD

**Issue by DAMWalrus** [davidvorona/gim-plugin#37]
Am i doing something wrong?

**Comment by davidvorona** [comment]
Make sure you've all set the same valid server address in the config field.

You can use my public server: https://gimp-server.herokuapp.com
or run your own.

If you've done this and it's still not working let me know and I can look into it. Bear in mind if you're in the overworld (say, Falador Park) and your friend is on another plane (like the Falador Mole Lair), then you won't see them on the map unless you manually click to it.

**Comment by davidvorona** [comment]
I just read that you said stats...sorry. Stats are pulled from OSRS Hiscores. OSRS Hiscores don't track every player...they ignore the lowest levels. You'll find on lower level accounts that you might pop in and out of the hiscores. I would assume the reason you don't see them is because the skills aren't high enough level.

**Comment by davidvorona** [comment]
![Screenshot (119)](https://user-images.githubusercontent.com/18473184/156965462-a19fd5b8-9888-4d5e-a88c-21be136e4c11.png)

Here's one of my fellow gimps by the way...if you look up his name on the hiscores, the stats showing in the panel match the ones in the hiscores. It makes a bit of sense: agility is there because he's got it to a decent level, and so Jagex records it in the hiscores. Runecraft is there (even at 19) because it's a much less popular skill...so the threshold for recording it in the hiscores is lower.

Of course it would probably be better to just manage stats myself, but it ends up being a lot more work. I might consider it, but really this is only a problem for low-level accounts.
