### ISSUE TITLE
stutter

### ISSUE THREAD

**Issue by samanthar0se** [davidvorona/gim-plugin#43]
I seem to be experiencing some stutter that stems from this plugin it's periodic and happens every few seconds. I spent some time trying to work on it but haven't found anything. Do you experience this at all? It's easily reproducible with my ping changes as it happens every time you ping, but I experience the same stutter on the live version of the plugin every few seconds.

**Comment by davidvorona** [comment]
There's probably something I should move off the main thread and into the EDT or something. I can look into it.

If you think you know what code causes it after you ping, try wrapping that code in `clientThread.invokeLater` and see if that helps.

**Comment by davidvorona** [comment]
Update: I took a closer look and there's definitely some threading issues with my code, primarily because of how I designed the websocket client. I patched the most prevalent stuttering, but a few things (like the longer stutter when you first log in) will have to wait a bit as I figure out exactly how to do it properly and keep the RL devs happy. I'm open to any suggestions or advice.

I'll try to bump the version and submit a release to RL sometime this week, hopefully with the threading issues completely solved. For now, to avoid the stuttering you can build it in dev mode.
